;;;;;;;;;;;;;;;;;;;;;;
; System error codes ;
;;;;;;;;;;;;;;;;;;;;;;

ERR_NOT_SUPPORTED   = $01
ERR_NO_MORE_DEVICES = $02
ERR_NO_SUCH_DEVICE  = $03
ERR_IO_ERROR        = $04
ERR_NO_MEDIA        = $05
ERR_DEVICE_BUSY     = $06
ERR_OUT_OF_MEMORY   = $07
ERR_INVALID_POINTER = $08
ERR_NO_FREE_INODES  = $09
ERR_NO_FREE_FILES   = $0A
ERR_FILE_NOT_FOUND  = $0B
ERR_NO_FREE_PROC    = $0C
ERR_BAD_FILE        = $0D
