(define memories
  '((memory bank0ram (address (#x0000 . #xe6ff)))
    (memory stack (address (#xe700 . #xeeff))
      (section stack))
    (memory directPage (address (#xef00 . #xefff))
      (section registers zzpage zpage))
    (memory bank0rom (address (#xf800 . #xffff))
      (section bootcode (hwvectors #xffe4)))
    (memory nearbank (address (#x10000 . #x1ffff))
      (placement-group near-bits (section near))
      (placement-group near-nobits (section buffers heap znear)))
    (memory lorom (address (#x100000 . #x10f7ff))
      (section code farcode cnear cfar inear switch data_init_table))
    (memory hirom (address (#x110000 . #x13ffff))
      (section hicode))
  (block stack (size #x800))
  (block heap (size #xF000))
  (base-address _DirectPageStart directPage 0)
  (base-address _NearBaseAddress nearbank 0)
))
